### ISSUE TITLE
this[kOnPacketAvailable] is not a function

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [openstf/node-minicap#3]
Don't work since the new version, the OnFrameAvailable is never called and it crashed on this :
```
0|server   | TypeError: this[kOnPacketAvailable] is not a function
0|server   |     at Parser.parse (/Users/jimmyramos/virtual-mobile-devices/server/node_modules/minicap/lib/parser.js:19:35)
0|server   |     at Socket.client.minicap_stream.on (/Users/jimmyramos/virtual-mobile-devices/server/socket_manager/io_operation/streaming_operation.js:114:16)
0|server   |     at Socket.emit (events.js:160:13)
0|server   |     at emitReadable_ (_stream_readable.js:520:10)
0|server   |     at emitReadable (_stream_readable.js:514:7)
0|server   |     at addChunk (_stream_readable.js:280:7)
0|server   |     at readableAddChunk (_stream_readable.js:256:11)
0|server   |     at Socket.Readable.push (_stream_readable.js:213:10)
0|server   |     at TCP.onread (net.js:602:20)
```

**Comment by sorccu** [comment]
Seems I somehow released the v0.2.1-0 prerelease as `latest`, which isn't correct. You should use v0.1.0. I've now fixed the `latest` tag.

**Comment by sorccu** [comment]
v0.2.x isn't compatible with v0.1.x.

**Comment by Nicolas-Menettrier** [comment]
Ok thanks
